In [30]:
import pandas as pd
import tensorflow as tf

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from tensorflow.python.keras.utils import np_utils

#데이터 입력
df = pd.read_csv('./VRK2_inhibitor_descriptor_Internal_dataset_dropunmane.csv')

#데이터 분류
dataset = df.values
X = dataset[:,0:-1]
Y = dataset[:,-1]

#X 표준화

scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)

#원-핫 인코딩
#Y_encoded = tf.keras.utils.to_categorical(Y)

#학습셋과 테스트셋을 나눔

X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size=0.2, random_state=0)

#KNN

clf_knn = KNeighborsClassifier(n_neighbors=7)
clf_knn.fit(X_train, Y_train)

knn_pred = clf_knn.predict(X_test)
#print(knn_pred)
accu = accuracy_score(Y_test, knn_pred)
print(accu)
knn_pred_total = clf_knn.predict(X)

conf_matrix = confusion_matrix(Y, knn_pred_total)
print(conf_matrix)

#class_report = classification_report(Y, knn_pred_total)
#print(class_report)

#Internal의 경우 k는 3으로. Train 정확도 0.65 Test 정확도 0.67

#출처:https://ysyblog.tistory.com/74

#추가 파라미터는? 피처 선택은?

0.5
[[ 6  0  0  0]
 [ 2  0  0  0]
 [ 8  0  0  0]
 [10  0  0  0]]


In [27]:
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import sys

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.inspection import permutation_importance
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import GridSearchCV

#데이터 입력
df = pd.read_csv('./VRK2_inhibitor_descriptor_Internal_dataset_dropunmane.csv')

#데이터 분류
dataset = df.values
X = dataset[:,0:-1]
Y = dataset[:,-1]

#X 표준화

scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)

#학습셋과 테스트셋을 나눔

X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size=0.2, random_state=0)

#파라미터 튜닝 

#k_param = range(1,20)
#train_acc_list = []
#test_acc_list = []

#for k in k_param:
#    classifier = KNeighborsClassifier(n_neighbors = k)
#    classifier.fit(X_train,Y_train)
#    pred_train = classifier.predict(X_train)
#    pred_test = classifier.predict(X_test)
#    train_acc_list.append(accuracy_score(Y_train,pred_train))
#    test_acc_list.append(accuracy_score(Y_test,pred_test))

#dic = {'k':k_param, 'Train 정확도': train_acc_list, 'Test 정확도': test_acc_list}

#acc_df = pd.DataFrame(dic)
#print(acc_df)

grid_params = {'n_neighbors' : [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16], 'weights' :['uniform', 'distance'], 
               'algorithm' :['auto', 'ball_tree', 'kd_tree', 'brute'], 'p':[1,2], 
               'metric' :['euclidean', 'manhattan','chebyshev','minkowski']}


knn = KNeighborsClassifier()

gs = GridSearchCV(knn, grid_params, cv=5)
gs.fit(X_train, Y_train)
print("Best Parameters : ", gs.best_params_)
print("Best Score : ", gs.best_score_)
print("Best Test Score : ", gs.score(X_test, Y_test))


#모델 set

#model = KNeighborsClassifier(n_neighbors = 3)
#model.fit(X_train,Y_train)

# perform permutation importance
#results = permutation_importance(model, X_train,Y_train, scoring='accuracy')
# get importance
#importance = results.importances_mean
# summarize feature importance
#sys.stdout = open('class5_nonzero.txt', 'w') 
#for i,v in enumerate(importance):
#    print('%0d, %.5f' % (i,v))
#sys.stdout.close()   
# plot feature importance
#plt.bar([x for x in range(len(importance))], importance)
#plt.show()

C:\Users\eunwoo\.conda\envs\Tensorflow\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


Best Parameters :  {'algorithm': 'auto', 'metric': 'euclidean', 'n_neighbors': 7, 'p': 1, 'weights': 'uniform'}
Best Score :  0.55
Best Test Score :  0.5


In [66]:
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.inspection import permutation_importance
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import GridSearchCV
from sklearn.feature_selection import SelectKBest, f_classif
from numpy import set_printoptions

#데이터 입력
df = pd.read_csv('./VRK2_inhibitor_descriptor_Internal_dataset_dropunmane.csv')

#데이터 분류
dataset = df.values
X = dataset[:,0:-1]
Y = dataset[:,-1]

#X 표준화

scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)

# feature extraction
#test = SelectKBest(score_func=f_classif, k=7)
#fit = test.fit(X_scaled, Y)
# summarize scores
#set_printoptions(precision=3)
#print(fit.scores_)
#a = pd.DataFrame(fit.scores_)
#print(a)
#b = a.dropna()
#print(b)
#c =b.T
#print(c)
#c.to_csv('./0309_feature_extraction.csv')
#features = fit.transform(X)

#학습셋과 테스트셋을 나눔

X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size=0.2, random_state=0)

#KNN
grid_params = {'n_neighbors' : [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16], 'weights' :['uniform', 'distance'], 
               'algorithm' :['auto', 'ball_tree', 'kd_tree', 'brute'], 'p':[1,2], 
               'metric' :['euclidean', 'manhattan','chebyshev','minkowski']}


knn = KNeighborsClassifier()

gs = GridSearchCV(knn, grid_params, cv=5)
gs.fit(X_train, Y_train)
print("Best Parameters : ", gs.best_params_)
print("Best Score : ", gs.best_score_)
print("Best Test Score : ", gs.score(X_test, Y_test))


knn_pred = gs.predict(X_test)
#print(knn_pred)
accu = accuracy_score(Y_test, knn_pred)
print(accu)
knn_pred_total = gs.predict(X_scaled)

conf_matrix = confusion_matrix(Y, knn_pred_total)
print(conf_matrix)


#X_new = SelectKBest(f_classif, k=1).fit_transform(X_scaled, Y)
#print(X_new)



C:\Users\eunwoo\.conda\envs\Tensorflow\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


Best Parameters :  {'algorithm': 'auto', 'metric': 'euclidean', 'n_neighbors': 7, 'p': 1, 'weights': 'uniform'}
Best Score :  0.55
Best Test Score :  0.5
0.5
[[6 0 0 0]
 [1 0 0 1]
 [4 0 0 4]
 [1 0 0 9]]


In [175]:
#pipiline 사용하기

import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import sys

from sklearn.neighbors import KNeighborsClassifier as kn
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.inspection import permutation_importance
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline , make_pipeline
from sklearn.feature_selection import SelectFromModel, f_classif, mutual_info_classif, SelectKBest, VarianceThreshold, SelectPercentile

#데이터 입력
df = pd.read_csv('./VRK2_inhibitor_descriptor_Internal_dataset_dropunmane.csv')

#데이터 분류
dataset = df.values
X = dataset[:,0:-1]
Y = dataset[:,-1]

#학습셋과 테스트셋을 나눔

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=10)

#파이프라인 생성

sel = SelectKBest()
clf = kn()
s = StandardScaler()
step = [('scaler', s),('sel',sel), ('kn', clf) ]
pipeline = Pipeline(step)
parameter = {'sel__k':np.arange(2200,2300,1),
             'kn__n_neighbors':range(1,15,1), 'kn__weights':['uniform','distance'], 'kn__p':[1,2] , 
             'kn__metric' :['euclidean', 'manhattan','chebyshev','minkowski'], 
             'kn__algorithm' :['auto', 'ball_tree', 'kd_tree', 'brute']}
grid = GridSearchCV(pipeline, param_grid = parameter, cv=5, scoring = 'accuracy', n_jobs = -1)
grid.fit(X_train, Y_train)

print("Best Parameters : ", grid.best_params_)
print("Best Score : ", grid.best_score_)
print("Best Test Score : ", grid.score(X_test, Y_test))

C:\Users\eunwoo\.conda\envs\Tensorflow\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


Best Parameters :  {'kn__algorithm': 'ball_tree', 'kn__metric': 'chebyshev', 'kn__n_neighbors': 9, 'kn__p': 1, 'kn__weights': 'distance', 'sel__k': 2255}
Best Score :  0.7
Best Test Score :  0.3333333333333333


C:\Users\eunwoo\.conda\envs\Tensorflow\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:114: UserWarning: Features [  28   30   41   55   59   65   69  363 1203 1207 1219 1223 1507 1510
 2355 2374 2680 2683 2685 2689 2690 2693 2694 2704 2705 2722 2752 2753
 2756 2757 2760 2761 2775 2782 2783 2798 2805 2806 2828 2836 2839 2849
 2860 2872 2875 2885 2895 2896 2897 2898 2899 2901 2903 2916 2919 2921
 2923 2926 2928 2929 2930 2931 2932 2935 2937 2941 2944 2946 2949 2951
 2954 2956 2957 2959 2961 2962 2965 2967 2970 2972 2973 2976 2983 2990
 2992 2998 3000 3007 3009 3016 3018 3019 3020 3021 3025 3027 3034 3036
 3039 3044 3046 3047 3049 3051 3055 3057 3060 3062 3066 3073 3080 3082
 3088 3090 3097 3099 3105 3108 3110 3151 3165 3166 3168 3169 3170 3171
 3183 3185 3186 3187 3188 3195 3196 3197 3198 3199 3200 3201 3202 3214
 3215 3216 3217 3218 3219 3221 3235 3236 3237 3238 3248 3250 3251 3252
 3253 3254 3255 3256 3257 3258 3259 3260 3261 3262 3277 3278 3279 3280
 3282 3283 32

In [ ]:
##knn:0.7넘는 게 없어서 패스 기본이 0.5

#Best Parameters :  {'algorithm': 'auto', 'metric': 'euclidean', 'n_neighbors': 7, 'p': 1, 'weights': 'uniform'} train 0.55 test 0.5

#SelectPercentile은 Best Parameters :  {'kn__algorithm': 'ball_tree', 'kn__metric': 'chebyshev', 'kn__n_neighbors': 9, 'kn__p': 1, 'kn__weights': 'distance', 'sel__percentile': 67.69000000000035}train 0.7 train 0.3

#VarianceThreshold는  {'kn__algorithm': 'ball_tree', 'kn__metric': 'chebyshev', 'kn__n_neighbors': 9, 'kn__p': 1, 'kn__weights': 'distance', 'sel__threshold': 1e-06} train 0.7 test 0.5

#SelectKBest는 