In [ ]:
#ANN StandardScaler 전처리

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, Dropout, BatchNormalization, Activation
from tensorflow.python.keras.utils import np_utils
from sklearn.model_selection import train_test_split, cross_val_score, cross_validate
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from tensorflow.python.keras import regularizers
from sklearn.metrics import accuracy_score, confusion_matrix
from tensorflow.python.keras.wrappers.scikit_learn import KerasClassifier


#seed 값 설정
np.random.seed(0)
tf.random.set_seed(0)

#데이터 입력
df = pd.read_csv('./VRK2_inhibitor_descriptor_Internal_dataset_dropunmane.csv')
df1 = pd.read_csv('./VRK2_inhibitor_descriptor_external_dataset_dropunmane.csv')
df2 = pd.concat([df, df1])

#데이터 분류
dataset = df.values
X = dataset[:,0:-1]
Y = dataset[:,-1]
#print(Y)

ex_data =df1.values
exX = ex_data[:,0:-1]
exY = ex_data[:,-1]

tot_data = df2.values
totX = tot_data[:,0:-1]
totY = tot_data[:,-1]

#X 표준화

scaler = StandardScaler()

scaler.fit(X)
X_scaled = scaler.transform(X)
exX_scaled = scaler.transform(exX)
totX_scaled = scaler.transform(totX)

#원-핫 인코딩
Y_encoded =np_utils.to_categorical(Y)
exY_encoded = np_utils.to_categorical(exY)

#학습셋과 테스트셋을 나눔

#X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, random_state=0)

#모델 설정

n_feat = X.shape[1]
n_class = len(set(Y))

model = Sequential()
model.add(Dense(100, input_dim=n_feat))
#model.add(BatchNormalization())
model.add(Activation('relu'))
#model.add(Dense(500))
#model.add(Activation('relu'))
#model.add(Dense(60))
#model.add(Activation('relu'))
model.add(Dense(n_class))
model.add(Activation('softmax'))

#model.summary()

#모델 컴파일
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

#모델 학습
model.fit(X_scaled,Y, epochs=10, batch_size=5)

#학습 평가

print(model.evaluate(X_scaled, Y)[1])
print(model.evaluate(exX_scaled, exY)[1])
print(model.evaluate(totX_scaled, totY)[1])

#testset 정확도 0.6 X 표준화시 0.4 X 정규화시 0.6

#데이터셋을 나눈 결과 정확도 0.5


#피처별 중요도, 파라미터 튜닝 필요

Epoch 1/10
6/6 [==============================] - 0s 2ms/step - loss: 3.1464 - accuracy: 0.3462
Epoch 2/10
6/6 [==============================] - 0s 3ms/step - loss: 1.5128 - accuracy: 0.6538
Epoch 3/10
6/6 [==============================] - 0s 3ms/step - loss: 2.1181 - accuracy: 0.8462
Epoch 4/10
6/6 [==============================] - 0s 3ms/step - loss: 1.4047 - accuracy: 0.7308
Epoch 5/10
6/6 [==============================] - 0s 3ms/step - loss: 0.7778 - accuracy: 0.8462
Epoch 6/10
6/6 [==============================] - 0s 4ms/step - loss: 1.3317 - accuracy: 0.8462
Epoch 7/10
6/6 [==============================] - 0s 4ms/step - loss: 0.3667 - accuracy: 0.8846
Epoch 8/10
6/6 [==============================] - 0s 3ms/step - loss: 0.5734 - accuracy: 0.8462
Epoch 9/10
6/6 [==============================] - 0s 3ms/step - loss: 0.2492 - accuracy: 0.9615
Epoch 10/10
1/1 [==============================] - 0s 1000us/step - loss: 0.3173 - accuracy: 0.9231
0.9230769276618958
1/1 [============

In [ ]:
#ANN MinMaxScaler 전처리

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, Dropout, BatchNormalization, Activation
from tensorflow.python.keras.utils import np_utils
from sklearn.model_selection import train_test_split, cross_val_score, cross_validate
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from tensorflow.python.keras import regularizers
from sklearn.metrics import accuracy_score, confusion_matrix


#seed 값 설정
np.random.seed(0)
tf.random.set_seed(0)

#데이터 입력
df = pd.read_csv('./VRK2_inhibitor_descriptor_Internal_dataset_dropunmane.csv')
df1 = pd.read_csv('./VRK2_inhibitor_descriptor_external_dataset_dropunmane.csv')
df2 = pd.concat([df, df1])

#데이터 분류
dataset = df.values
X = dataset[:,0:-1]
Y = dataset[:,-1]
#print(Y)

ex_data =df1.values
exX = ex_data[:,0:-1]
exY = ex_data[:,-1]

tot_data = df2.values
totX = tot_data[:,0:-1]
totY = tot_data[:,-1]

#X 표준화

scaler = MinMaxScaler()

scaler.fit(X)
X_scaled = scaler.transform(X)
exX_scaled = scaler.transform(exX)
totX_scaled = scaler.transform(totX)

#원-핫 인코딩
Y_encoded =np_utils.to_categorical(Y)
exY_encoded = np_utils.to_categorical(exY)

#학습셋과 테스트셋을 나눔

#X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, random_state=0)

#모델 설정

n_feat = X.shape[1]
n_class = len(set(Y))

model = Sequential()
model.add(Dense(100, input_dim=n_feat))
#model.add(BatchNormalization())
model.add(Activation('relu'))
#model.add(Dense(500))
#model.add(Activation('relu'))
#model.add(Dense(60))
#model.add(Activation('relu'))
model.add(Dense(n_class))
model.add(Activation('softmax'))

#model.summary()

#모델 컴파일
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

#모델 학습
model.fit(X_scaled,Y, epochs=20, batch_size=5)

#학습 평가

print(model.evaluate(X_scaled, Y)[1])
print(model.evaluate(exX_scaled, exY)[1])
print(model.evaluate(totX_scaled, totY)[1])

#testset 정확도 0.6 X 표준화시 0.4 X 정규화시 0.6

#데이터셋을 나눈 결과 정확도 0.5


#피처별 중요도, 파라미터 튜닝 필요

Epoch 1/20
6/6 [==============================] - 0s 3ms/step - loss: 2.1249 - accuracy: 0.1923
Epoch 2/20
6/6 [==============================] - 0s 3ms/step - loss: 1.4861 - accuracy: 0.5385
Epoch 3/20
6/6 [==============================] - 0s 3ms/step - loss: 1.0565 - accuracy: 0.5000
Epoch 4/20
6/6 [==============================] - 0s 4ms/step - loss: 0.8643 - accuracy: 0.7308
Epoch 5/20
6/6 [==============================] - 0s 4ms/step - loss: 1.0524 - accuracy: 0.6154
Epoch 6/20
6/6 [==============================] - 0s 4ms/step - loss: 0.6245 - accuracy: 0.7308
Epoch 7/20
6/6 [==============================] - 0s 4ms/step - loss: 0.5373 - accuracy: 0.7692
Epoch 8/20
6/6 [==============================] - 0s 4ms/step - loss: 0.4891 - accuracy: 0.6923
Epoch 9/20
6/6 [==============================] - 0s 4ms/step - loss: 0.4217 - accuracy: 0.8462
Epoch 10/20
6/6 [==============================] - 0s 3ms/step - loss: 0.3935 - accuracy: 0.8462
Epoch 11/20
6/6 [======================

In [ ]:


import sklearn
print(sklearn.__version__)

0.23.2


In [ ]:
#하이퍼파라미터 실습 (출처: https://towardsdatascience.com/simple-guide-to-hyperparameter-tuning-in-neural-networks-3fe03dad8594)

import tensorflow as tf
import keras

from keras import layers
from keras import models
from keras import utils
from keras.layers import Dense
from keras.models import Sequential
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import Activation
from keras.regularizers import l2
from keras.optimizers import SGD
from keras.optimizers import RMSprop

from keras.callbacks import LearningRateScheduler
from keras.callbacks import History

from keras import losses
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler, StandardScaler

#print(tf.__version__): 2.3.0
#print(tf.keras.__version__) :2.4.0

# fix random seed for reproducibility
np.random.seed(5)

#데이터 입력
df = pd.read_csv('./VRK2_inhibitor_descriptor_Internal_dataset_dropunmane.csv')
df1 = pd.read_csv('./VRK2_inhibitor_descriptor_external_dataset_dropunmane.csv')
df2 = pd.concat([df, df1])

#데이터 분류
dataset = df.values
X = dataset[:,0:-1]
Y = dataset[:,-1]

ex_data =df1.values
exX = ex_data[:,0:-1]
exY = ex_data[:,-1]

tot_data = df2.values
totX = tot_data[:,0:-1]
totY = tot_data[:,-1]

#X 표준화

scaler = MinMaxScaler()

scaler.fit(X)
X_scaled = scaler.transform(X)
exX_scaled = scaler.transform(exX)
totX_scaled = scaler.transform(totX)

#epochs=60
#learning_rate = 0.1
#decay_rate = learning_rate / epochs
#momentum = 0.8
#n_class = len(set(Y))

#sgd = SGD(lr=learning_rate, momentum=momentum, decay=decay_rate, nesterov=False)

# build the model

#input_dim = X_scaled.shape[1]

#lr_model = Sequential()
#lr_model.add(Dense(64, activation=tf.nn.relu, kernel_initializer='uniform', 
                #input_dim = input_dim)) 
#lr_model.add(Dropout(0.1))
#lr_model.add(Dense(64, kernel_initializer='uniform', activation=tf.nn.relu))
#lr_model.add(Dense(n_class, kernel_initializer='uniform', activation=tf.nn.softmax))

# compile the model
#lr_model.compile(loss='sparse_categorical_crossentropy',optimizer=sgd,metrics=['accuracy'])

# Fit the model
#batch_size = int(input_dim/100)

#lr_model_history = lr_model.fit(X_scaled, Y,batch_size=batch_size,epochs=epochs,verbose=1,validation_data=(exX_scaled, exY))

# Plot the loss function
#fig, ax = plt.subplots(1, 1, figsize=(10,6))
#ax.plot(np.sqrt(lr_model_history.history['loss']), 'r', label='train')
#ax.plot(np.sqrt(lr_model_history.history['val_loss']), 'b' ,label='val')
#ax.set_xlabel(r'Epoch', fontsize=20)
#ax.set_ylabel(r'Loss', fontsize=20)
#ax.legend()
#ax.tick_params(labelsize=20)

# Plot the accuracy
#fig, ax = plt.subplots(1, 1, figsize=(10,6))
#ax.plot(np.sqrt(lr_model_history.history['accuracy']), 'r', label='train')
#ax.plot(np.sqrt(lr_model_history.history['val_accuracy']), 'b' ,label='val')
#ax.set_xlabel(r'Epoch', fontsize=20)
#ax.set_ylabel(r'Accuracy', fontsize=20)
#ax.legend()
#ax.tick_params(labelsize=20)

#여기까지 시행한 결과 Epoch 50일 때가 가장 괜찮음

#learning rate 교체

epochs = 25
learning_rate = 0.1 # initial learning rate는 0.1
decay_rate = 0.1
momentum = 0.8

# define the optimizer function
sgd = SGD(lr=learning_rate, momentum=momentum, decay=decay_rate, nesterov=False)

input_dim = X_scaled.shape[1]
batch_size = 90
n_class = len(set(Y))

# build the model
exponential_decay_model = Sequential()
exponential_decay_model.add(Dense(290, activation=tf.nn.relu, kernel_initializer='uniform', input_dim = input_dim))
exponential_decay_model.add(Dropout(0.3))
exponential_decay_model.add(Dense(64, kernel_initializer='uniform', activation=tf.nn.relu))
exponential_decay_model.add(Dense(n_class, kernel_initializer='uniform', activation=tf.nn.softmax))

# compile the model
exponential_decay_model.compile(loss='sparse_categorical_crossentropy', 
                                optimizer=sgd, 
                                metrics=['accuracy'])
                                
# define the learning rate change 
def exp_decay(epoch):
    lrate = learning_rate * np.exp(-decay_rate*epoch)
    print(lrate)
    return lrate
    
# learning schedule callback
loss_history = History()
lr_rate = LearningRateScheduler(exp_decay)
callbacks_list = [loss_history, lr_rate]

# you invoke the LearningRateScheduler during the .fit() phase
exponential_decay_model_history = exponential_decay_model.fit(X_scaled, Y,batch_size=batch_size,epochs=epochs,
                                                              callbacks=callbacks_list,verbose=1,
                                                              validation_data=(exX_scaled, exY))

print(exponential_decay_model.evaluate(X_scaled, Y)[1])
print(exponential_decay_model.evaluate(exX_scaled, exY)[1])
print(exponential_decay_model.evaluate(totX_scaled, totY)[1])

0.1
Epoch 1/25
1/1 [==============================] - 0s 153ms/step - loss: 1.3833 - accuracy: 0.3077 - val_loss: 1.2941 - val_accuracy: 0.3333
0.09048374180359596
Epoch 2/25
1/1 [==============================] - 0s 16ms/step - loss: 1.3520 - accuracy: 0.4615 - val_loss: 1.2797 - val_accuracy: 0.5000
0.0818730753077982
Epoch 3/25
1/1 [==============================] - 0s 60ms/step - loss: 1.3211 - accuracy: 0.4615 - val_loss: 1.2666 - val_accuracy: 0.5000
0.0740818220681718
Epoch 4/25
1/1 [==============================] - 0s 22ms/step - loss: 1.2821 - accuracy: 0.4231 - val_loss: 1.2609 - val_accuracy: 0.5000
0.06703200460356394
Epoch 5/25
1/1 [==============================] - 0s 32ms/step - loss: 1.2168 - accuracy: 0.5385 - val_loss: 1.2670 - val_accuracy: 0.5000
0.06065306597126335
Epoch 6/25
1/1 [==============================] - ETA: 0s - loss: 1.1726 - accuracy: 0.53 - 0s 30ms/step - loss: 1.1726 - accuracy: 0.5385 - val_loss: 1.2845 - val_accuracy: 0.5000
0.05488116360940264
E

In [35]:
#하이퍼파라미터 실습 2(출처:https://machinelearningmastery.com/grid-search-hyperparameters-deep-learning-models-python-keras/)


# Use scikit-learn to grid search the batch size and epochs

import numpy as np
import pandas as pd
import joblib

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.layers import Dropout
from keras.constraints import maxnorm
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, roc_auc_score, f1_score
from keras.models import load_model
from keras.optimizers import Adadelta
from scipy.stats import randint, uniform, loguniform
from imblearn.over_sampling import SMOTE

# fix random seed for reproducibility

seed = 0
np.random.seed(seed)

#데이터 입력
df = pd.read_csv('/content/drive/MyDrive/Inhibitor classification/Inhibitor/PA/MORDRED_2D/PA_morgan_2D_apppendscore_dropsmiles.csv')
data = pd.read_csv('/content/drive/MyDrive/Inhibitor classification/Inhibitor/PA/MORDRED_2D/PAOthers_morgan_2D_apppendscore_dropsmiles.csv')

#데이터 분류
dataset = df.values
X = dataset[:,0:-1]
Y = dataset[:,-1]

data = data.values
X_others =data[:,0:-1]
Y_others =data[:,-1]

#X 표준화

scaler = RobustScaler()

X_scaled = scaler.fit_transform(X)
X_others_scaled = scaler.transform(X_others)

#Oversampling using SMOTE

#smote = SMOTE(random_state=0)
#X_over, Y_over = smote.fit_sample(X_scaled, Y)

# Function to create model, required for KerasClassifier
input_dim = X_scaled.shape[1]
n_class = len(set(Y))

def create_model(activation='relu', activation1='softmax', optimizer='adam'):
   # create model
    model = Sequential()
    model.add(Dense(100, input_dim=input_dim , activation=activation))
    model.add(Dense(n_class, activation=activation1))
    model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(create_model, epochs = 100, batch_size = 10, verbose=0)

# define the grid search parameters

param_grid = {'activation':['softmax', 'softplus', 'softsign', 'relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'linear'], 
              'activation1':['softmax', 'softplus', 'softsign', 'relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'linear'], 
              'optimizer':['SGD', 'RMSprop', 'Adagrad', 'Adadelta', 'Adam', 'Adamax', 'Nadam']}
grid = GridSearchCV(model, param_grid, n_jobs=-1, cv=5)
grid_result = grid.fit(X_scaled, Y)

#정해진 파라미터 'optimizer': 'Adadelta' , 'init_mode': 'lecun_uniform', activation: 'sigmoid' , dropout: 0.3, constraint:5, neuron:290

# summarize results
#print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
#means = grid_result.cv_results_['mean_test_score']
#stds = grid_result.cv_results_['std_test_score']
#params = grid_result.cv_results_['params']
#for mean, stdev, param in zip(means, stds, params):
#    print("%f (%f) with: %r" % (mean, stdev, param))
print(grid_result.best_params_)

ann = grid_result.best_estimator_   
   
#print(ann.evaluate(X_scaled, Y)[1])
#print(ann.evaluate(exX_scaled, exY)[1])
#print(ann.evaluate(totX_scaled, totY)[1])   

#결과리포트 생성(단일)

#def get_clf_eval(y_test=None, pred=None):
#    confusion = confusion_matrix(y_test, pred)
#    accuracy = accuracy_score(y_test, pred)
#   print('오차행렬')
#    print(confusion)
#    print('정확도: {0:.4f}'.format(accuracy))

#def get_model_train_eval(model, ftr_train=None, ftr_test=None, ftr_tot=None, tgt_train=None, tgt_test=None, tgt_tot=None):
#    model.fit(ftr_train, tgt_train)
#    pred = model.predict(ftr_train)
#    predex = model.predict(ftr_test)
#    predtot = model.predict(ftr_tot)
#    get_clf_eval(tgt_train, pred)
#    get_clf_eval(tgt_test, predex)
#    get_clf_eval(tgt_tot, predtot)
    
#get_model_train_eval(ann, ftr_train=X_scaled, ftr_test=exX_scaled, ftr_tot=totX_scaled, tgt_train=Y, tgt_test=exY, tgt_tot=totY) 

#top 5 리포트 작성

def report(results, n_top=5):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("") #여기에 accu, conf 추가해야 함
            
report(grid.cv_results_)            
    
#정확도와 혼동함수 생성

pred = ann.predict(X_scaled)
accuracy = accuracy_score(Y, pred)
print('ann 정확도: {0:.4f}'.format(accuracy))
conf_matrix = confusion_matrix(Y, pred, labels=[0,1,2,3])
print(conf_matrix)
#conf_matrix_nor = confusion_matrix(Y, pred)/60
#print(conf_matrix_nor)

pred2 = ann.predict(X_others_scaled)
accuracy2 = accuracy_score(Y_others, pred2)
print('ann others 정확도: {0:.4f}'.format(accuracy2))
conf_matrix2 = confusion_matrix(Y_others, pred2, labels=[0,1,2,3])
print(conf_matrix2)
#conf_matrix2_nor = confusion_matrix(exY, pred2)/14
#print(conf_matrix2_nor)

#pred3 = ann.predict(totX_scaled)
#accuracy = accuracy_score(totY, pred3)
#print('ann 전체 정확도: {0:.4f}'.format(accuracy))
#conf_matrix3 = confusion_matrix(totY, pred3)
#print(conf_matrix3)
#conf_matrix3_nor = confusion_matrix(totY, pred3)/74
#print(conf_matrix3_nor)    
    
#모델 저장

#ann.model.save('/content/drive/MyDrive/Inhibitor classification/Inhibitor/PA/Classification/ANN/PA_ann_0406_02.h5')

#0324 total 0.93 test 0.64 0324_2 total 0.95 test 0.71(그치만 과적합) 0324_3 total 0.96 test 0.79

{'activation': 'softmax', 'activation1': 'hard_sigmoid', 'optimizer': 'SGD'}
Model with rank: 1
Parameters: {'activation': 'softmax', 'activation1': 'hard_sigmoid', 'optimizer': 'SGD'}

Model with rank: 2
Parameters: {'activation': 'softmax', 'activation1': 'sigmoid', 'optimizer': 'SGD'}

Model with rank: 3
Parameters: {'activation': 'softmax', 'activation1': 'softmax', 'optimizer': 'SGD'}

Model with rank: 4
Parameters: {'activation': 'sigmoid', 'activation1': 'softmax', 'optimizer': 'Adadelta'}

Model with rank: 5
Parameters: {'activation': 'softmax', 'activation1': 'softplus', 'optimizer': 'SGD'}

ann 정확도: 0.5743
[[ 0 21  0  0]
 [ 0 58  0  0]
 [ 0 10  0  0]
 [ 0 12  0  0]]
ann others 정확도: 0.0000
[[ 0 42  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 8899457230196092810, name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 15703311680
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 11924361053094878025
 physical_device_desc: "device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0"]

In [11]:
#ANN 정해진 파라미터로 실험

import numpy as np
import pandas as pd
import joblib

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, StratifiedKFold
from sklearn.preprocessing import StandardScaler, RobustScaler
from keras.models import Sequential, load_model
from keras.layers import Dense
from sklearn.metrics import accuracy_score, confusion_matrix
from keras.models import load_model

from google.colab import drive
drive.mount('/content/drive')

# fix random seed for reproducibility

seed = 0
np.random.seed(seed)

#데이터 입력
df = pd.read_csv('/content/drive/MyDrive/Inhibitor classification/Inhibitor/PA/rdkit_fingerprint/PA_rdkitfingerprint_apppendscore_dropsmiles.csv')

#데이터 분류
dataset = df.values
X = dataset[:,0:-1]
Y = dataset[:,-1]

#X 표준화

scaler = RobustScaler()

X_scaled = scaler.fit_transform(X)

#데이터셋 쪼개기

n_fold = 5
skf = StratifiedKFold(n_splits=n_fold, shuffle=True, random_state=seed)

#빈 accu 배열

accuracy = []

#모델 설정, 컴파일, 실행

n_feat = X_scaled.shape[1]
n_class = len(set(Y))

for train,test in skf.split(X_scaled,Y):
    model = Sequential()
    model.add(Dense(500, input_dim=n_feat , activation='relu'))
    model.add(Dense(n_class, activation='softmax'))
    model.compile(loss='sparse_categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])
    model.fit(X[train],Y[train], epochs=100, batch_size=10)
    k_accuracy = "%.4f" % (model.evaluate(X_scaled, Y)[1])
    accuracy.append(k_accuracy)

 #결과 출력
 
print('\n %.f fold accuracy:' % n_fold, accuracy)

 #모델 저장   

model.save('/content/drive/MyDrive/Inhibitor classification/Inhibitor/PA/Classification/ANN/PA_ann_0406_01.h5')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Epoch 1/100
8/8 [==============================] - 0s 2ms/step - loss: 4.1081 - accuracy: 0.4065
Epoch 2/100
8/8 [==============================] - 0s 2ms/step - loss: 2.1736 - accuracy: 0.4277
Epoch 3/100
8/8 [==============================] - 0s 2ms/step - loss: 1.4630 - accuracy: 0.5622
Epoch 4/100
8/8 [==============================] - 0s 2ms/step - loss: 0.5552 - accuracy: 0.7978
Epoch 5/100
8/8 [==============================] - 0s 2ms/step - loss: 0.4556 - accuracy: 0.8816
Epoch 6/100
8/8 [==============================] - 0s 2ms/step - loss: 0.4065 - accuracy: 0.8615
Epoch 7/100
8/8 [==============================] - 0s 2ms/step - loss: 0.3848 - accuracy: 0.8355
Epoch 8/100
8/8 [==============================] - 0s 2ms/step - loss: 0.6061 - accuracy: 0.6969
Epoch 9/100
8/8 [==============================] - 0s 2ms/step - loss: 0.3985 - accuracy: 0.833

In [ ]:
#핸즈온 머신러닝을 활용한 ann 튜닝

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import joblib

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.layers import Dropout, InputLayer
from keras.constraints import maxnorm
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, roc_auc_score, f1_score
from keras.models import load_model
from keras.optimizers import SGD
from scipy.stats import randint, uniform, loguniform
from imblearn.over_sampling import SMOTE
from keras.callbacks import EarlyStopping
from scipy.stats import reciprocal

# fix random seed for reproducibility

seed = 7
np.random.seed(seed)

#데이터 입력
df = pd.read_csv('/content/drive/MyDrive/Inhibitor classification/Inhibitor/PA/csv/PA_inhibitor_descriptor_internal_dataset.csv')
df1 = pd.read_csv('/content/drive/MyDrive/Inhibitor classification/Inhibitor/PA/csv/PA_inhibitor_descriptor_external_dataset.csv')
df2 = pd.concat([df, df1])

#데이터 분류
dataset = df.values
X = dataset[:,0:-1]
Y = dataset[:,-1]

ex_data =df1.values
exX = ex_data[:,0:-1]
exY = ex_data[:,-1]

tot_data = df2.values
totX = tot_data[:,0:-1]
totY = tot_data[:,-1]

#X 표준화

scaler = StandardScaler()

scaler.fit(X)
X_scaled = scaler.transform(X)
exX_scaled = scaler.transform(exX)
totX_scaled = scaler.transform(totX)

#모델 만들고 컴파일하는 함수 생성

input_dim = X_scaled.shape[1]
n_class = 4

def build_model(n_hidden=1, n_neurons=30, learning_rate=3e-3, input_shape=input_dim):
    model = Sequential()
    model.add(InputLayer(input_shape=input_dim))
    for layer in range(n_hidden):
        model.add(Dense(n_neurons, activation='relu'))
    model.add(Dense(n_class))
    optimizer = SGD(learning_rate)
    model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

#함수 파라미터 튜닝에 적용

clf = KerasClassifier(build_model) 

clf.fit(X_scaled, Y, epochs=100, batch_size = 10, validation_data=(exX_scaled, exY), callbacks=[EarlyStopping(patience=10)])
mse_test = clf.score(exX_scaled, exY)
pred = clf.predict(exX_scaled)  

param_distribs = {"n_hidden": [0,1,2,3], "n_neurons": [10,20,30,40,50,60,70,80,90,100],'learning_rate':[3e-5, 3e-4, 3e-3, 2e-3, 1e-3]}

clf_cv = RandomizedSearchCV(clf, param_distribs, n_iter=20, cv=5)
clf_cv.fit(X_scaled, Y, epochs=100, validation_data=(exX_scaled, exY), callbacks=[EarlyStopping(patience=10)])  

#top20 결과 리포트

def report(results, n_top=20):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("") #여기에 accu, conf 추가해야 함
            
report(clf_cv.cv_results_) 

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Epoch 1/100
10/10 [==============================] - 1s 24ms/step - loss: 9.4286 - accuracy: 0.3427 - val_loss: 10.6730 - val_accuracy: 0.3000
Epoch 2/100
10/10 [==============================] - 0s 7ms/step - loss: 9.4143 - accuracy: 0.3052 - val_loss: 9.8224 - val_accuracy: 0.3000
Epoch 3/100
10/10 [==============================] - 0s 6ms/step - loss: 7.4907 - accuracy: 0.3960 - val_loss: 9.0913 - val_accuracy: 0.3000
Epoch 4/100
10/10 [==============================] - 0s 8ms/step - loss: 6.9714 - accuracy: 0.4250 - val_loss: 9.8498 - val_accuracy: 0.3000
Epoch 5/100
10/10 [==============================] - 0s 6ms/step - loss: 6.8797 - accuracy: 0.4364 - val_loss: 9.7723 - val_accuracy: 0.3000
Epoch 6/100
10/10 [==============================] - 0s 7ms/step - loss: 7.8309 - accuracy: 0.3967 - val_loss: 10.5140 - val_accuracy: 0.3000
Epoch 7/100
10/10 [===

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
3/3 [==============================] - 0s 22ms/step - loss: 4.8525 - accuracy: 0.3195 - val_loss: 5.0943 - val_accuracy: 0.3500
Epoch 32/100
3/3 [==============================] - 0s 23ms/step - loss: 4.7100 - accuracy: 0.3117 - val_loss: 5.0752 - val_accuracy: 0.3500
Epoch 33/100
3/3 [==============================] - 0s 22ms/step - loss: 4.5699 - accuracy: 0.3312 - val_loss: 4.5519 - val_accuracy: 0.3500
Epoch 34/100
3/3 [==============================] - 0s 26ms/step - loss: 4.3846 - accuracy: 0.3117 - val_loss: 5.4285 - val_accuracy: 0.3000
Epoch 35/100
3/3 [==============================] - 0s 23ms/step - loss: 3.6661 - accuracy: 0.3138 - val_loss: 3.7007 - val_accuracy: 0.4000
Epoch 36/100
3/3 [==============================] - 0s 22ms/step - loss: 4.9374 - accuracy: 0.3234 - val_loss: 4.1106 - val_accuracy: 0.4000
Epoch 37/100
3/3 [==============================] - 0s 23ms/step - loss: 4.0485 - accuracy: 0.3351 - val_loss: 3.7247 - val_accurac

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

#하이퍼파라미터 실습 2(출처:https://machinelearningmastery.com/grid-search-hyperparameters-deep-learning-models-python-keras/)


# Use scikit-learn to grid search the batch size and epochs

import numpy as np
import pandas as pd
import joblib
import scipy

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler, RobustScaler
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.layers import Dropout
from keras.constraints import maxnorm
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, roc_auc_score, f1_score
from keras.models import load_model
from keras.optimizers import Adadelta
from imblearn.over_sampling import SMOTE
from scipy.stats import uniform as sp_randFloat
from scipy.stats import randint as sp_randInt  

# fix random seed for reproducibility

seed = 7
np.random.seed(seed)

#데이터 입력
df = pd.read_csv('/content/drive/MyDrive/Inhibitor classification/Inhibitor/PA/csv/PA_internal_withothers.csv')
df1 = pd.read_csv('/content/drive/MyDrive/Inhibitor classification/Inhibitor/PA/csv/PA_external_withothers.csv')
df2 = pd.concat([df, df1])

#데이터 분류
dataset = df.values
X = dataset[:,0:-1]
Y = dataset[:,-1]

ex_data =df1.values
exX = ex_data[:,0:-1]
exY = ex_data[:,-1]

tot_data = df2.values
totX = tot_data[:,0:-1]
totY = tot_data[:,-1]

#X 표준화

scaler = RobustScaler()

X_scaled = scaler.fit_transform(X)
exX_scaled = scaler.transform(exX)
totX_scaled = scaler.transform(totX)

#Oversampling using SMOTE

#smote = SMOTE(random_state=0)
#X_over, Y_over = smote.fit_sample(X_scaled, Y)

# Function to create model, required for KerasClassifier
input_dim = X_scaled.shape[1]
n_class = len(set(Y))

def create_model(activation='relu'):
   # create model
    model = Sequential()
    model.add(Dense(10, input_dim=input_dim , activation=activation))
    model.add(Dense(n_class, activation='softmax'))
    model.compile(loss='sparse_categorical_crossentropy', optimizer='RMSprop', metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(create_model, batch_size = 10, epochs = 100, verbose=0)

# define the grid search parameters

activation = ['softmax', 'softplus', 'softsign', 'relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'linear']
param_grid = dict(activation=activation)
grid =GridSearchCV(model, param_grid, n_jobs=-1, cv=5)
grid_result = grid.fit(X_scaled, Y)

# summarize results
#print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
#means = grid_result.cv_results_['mean_test_score']
#stds = grid_result.cv_results_['std_test_score']
#params = grid_result.cv_results_['params']
#for mean, stdev, param in zip(means, stds, params):
#    print("%f (%f) with: %r" % (mean, stdev, param))
print(grid_result.best_params_)

ann = grid_result.best_estimator_   
   
#print(ann.evaluate(X_scaled, Y)[1])
#print(ann.evaluate(exX_scaled, exY)[1])
#print(ann.evaluate(totX_scaled, totY)[1])   

#결과리포트 생성(단일)

def get_clf_eval(y_test=None, pred=None):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    print('오차행렬')
    print(confusion)
    print('정확도: {0:.4f}'.format(accuracy))

def get_model_train_eval(model, ftr_train=None, ftr_test=None, ftr_tot=None, tgt_train=None, tgt_test=None, tgt_tot=None):
    model.fit(ftr_train, tgt_train)
    pred = model.predict(ftr_train)
    predex = model.predict(ftr_test)
    predtot = model.predict(ftr_tot)
    get_clf_eval(tgt_train, pred)
    get_clf_eval(tgt_test, predex)
    get_clf_eval(tgt_tot, predtot)
    
get_model_train_eval(ann, ftr_train=X_scaled, ftr_test=exX_scaled, ftr_tot=totX_scaled, tgt_train=Y, tgt_test=exY, tgt_tot=totY) 

#top 3 리포트 작성

def report(results, n_top=20):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("") #여기에 accu, conf 추가해야 함
            
report(grid.cv_results_)            
    
#정확도와 혼동함수 생성

#pred = ann.predict(X_scaled)
#accuracy = accuracy_score(Y, pred)
#print('ann 내부 정확도: {0:.4f}'.format(accuracy))
#conf_matrix = confusion_matrix(Y, pred)
#print(conf_matrix)
#conf_matrix_nor = confusion_matrix(Y, pred)/60
#print(conf_matrix_nor)

#pred2 = ann.predict(exX_scaled)
#accuracy = accuracy_score(exY, pred2)
#print('ann 외부 정확도: {0:.4f}'.format(accuracy))
#conf_matrix2 = confusion_matrix(exY, pred2)
#print(conf_matrix2)
#conf_matrix2_nor = confusion_matrix(exY, pred2)/14
#print(conf_matrix2_nor)

#pred3 = ann.predict(totX_scaled)
#accuracy = accuracy_score(totY, pred3)
#print('ann 전체 정확도: {0:.4f}'.format(accuracy))
#conf_matrix3 = confusion_matrix(totY, pred3)
#print(conf_matrix3)
#conf_matrix3_nor = confusion_matrix(totY, pred3)/74
#print(conf_matrix3_nor)    
    
#모델 저장

ann.model.save('PA_ann_0401_2.h5')

#0324 total 0.93 test 0.64 0324_2 total 0.95 test 0.71(그치만 과적합) 0324_3 total 0.96 test 0.79

#0331&0331_2 0.9 0.40 0.81  0331_3 0.48 0.65 0.51 0331_4 0.91 0.42 0.82 0404_1 0.82 0.53 0.77

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
{'activation': 'relu'}
오차행렬
[[64  0  0  0]
 [ 8 37  0  0]
 [ 0  0  8  0]
 [ 0  0  0 10]]
정확도: 0.9370
오차행렬
[[ 8  3  0  0]
 [10  3  0  0]
 [ 0  0  1  1]
 [ 1  0  0  1]]
정확도: 0.4643
오차행렬
[[72  3  0  0]
 [18 40  0  0]
 [ 0  0  9  1]
 [ 1  0  0 11]]
정확도: 0.8516
Model with rank: 1
Parameters: {'activation': 'relu'}

Model with rank: 2
Parameters: {'activation': 'linear'}

Model with rank: 3
Parameters: {'activation': 'tanh'}

Model with rank: 4
Parameters: {'activation': 'sigmoid'}

Model with rank: 5
Parameters: {'activation': 'hard_sigmoid'}

Model with rank: 6
Parameters: {'activation': 'softmax'}

Model with rank: 7
Parameters: {'activation': 'softsign'}

Model with rank: 8
Parameters: {'activation': 'softplus'}



/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import joblib
import tensorflow as tf

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler, RobustScaler
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.layers import Dropout
from keras.constraints import maxnorm
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, roc_auc_score, f1_score
from keras.models import load_model
from keras.optimizers import Adadelta
from scipy.stats import randint, uniform, loguniform
from imblearn.over_sampling import SMOTE
from tensorflow.python.keras.utils import np_utils

# fix random seed for reproducibility

seed = 7
np.random.seed(seed)

#데이터 입력
df = pd.read_csv('/content/drive/MyDrive/Inhibitor classification/Inhibitor/PA/csv/PA_internal_withothers.csv')
df1 = pd.read_csv('/content/drive/MyDrive/Inhibitor classification/Inhibitor/PA/csv/PA_external_withothers.csv')
df2 = pd.concat([df, df1])

#데이터 분류
dataset = df.values
X = dataset[:,0:-1]
Y = dataset[:,-1]

ex_data =df1.values
exX = ex_data[:,0:-1]
exY = ex_data[:,-1]

tot_data = df2.values
totX = tot_data[:,0:-1]
totY = tot_data[:,-1]

#X 표준화

scaler = RobustScaler()

X_scaled = scaler.fit_transform(X)
exX_scaled = scaler.transform(exX)
totX_scaled = scaler.transform(totX)

#Y 인코딩

Y_encoded = tf.keras.utils.to_categorical(Y)
exY_encoded = tf.keras.utils.to_categorical(exY)
totY_encoded = tf.keras.utils.to_categorical(totY)

#모델 생성

input_dim = X_scaled.shape[1]
n_class = len(set(Y))

model = Sequential()
model.add(Dense(50, input_dim=input_dim , activation='relu'))
model.add(Dense(n_class))
model.compile(loss='MSE', optimizer='adam', metrics=['accuracy'])

#모델 학습
model.fit(X_scaled,Y_encoded, epochs=200, batch_size=5)

#학습 평가

print(model.evaluate(X_scaled, Y_encoded)[1])
print(model.evaluate(exX_scaled, exY_encoded)[1])
print(model.evaluate(totX_scaled, totY_encoded)[1])

#모델 저장

model.save('PA_ann_0401_.h5')

#0401_3 0.74 0.53 0.70


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Epoch 1/200
26/26 [==============================] - 0s 2ms/step - loss: 15.8912 - accuracy: 0.2324
Epoch 2/200
26/26 [==============================] - 0s 2ms/step - loss: 14.4963 - accuracy: 0.4104
Epoch 3/200
26/26 [==============================] - 0s 2ms/step - loss: 5.5547 - accuracy: 0.2261
Epoch 4/200
26/26 [==============================] - 0s 2ms/step - loss: 5.9596 - accuracy: 0.3227
Epoch 5/200
26/26 [==============================] - 0s 2ms/step - loss: 2.8726 - accuracy: 0.4543
Epoch 6/200
26/26 [==============================] - 0s 2ms/step - loss: 0.8661 - accuracy: 0.4748
Epoch 7/200
26/26 [==============================] - 0s 2ms/step - loss: 0.5650 - accuracy: 0.5814
Epoch 8/200
26/26 [==============================] - 0s 2ms/step - loss: 0.4738 - accuracy: 0.4653
Epoch 9/200
26/26 [==============================] - 0s 2ms/step - loss: 0.36

In [ ]:
print(list(range(1,100,1)))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [ ]:
from scipy.stats import uniform as sp_randFloat
from scipy.stats import randint as sp_randInt  

Float = sp_randFloat(1e-5, 1e-4)
print(Float)

In [ ]:
import numpy as np

print(list(np.random.uniform(0.8, 1, 30)))

[0.9910936646005852, 0.9365827708750836, 0.8106257381345916, 0.8617705369727595, 0.9185189374646746, 0.8470240814514929, 0.9929941999072254, 0.9890096447585588, 0.9696801761675378, 0.8944647992576805, 0.9682953429796795, 0.8262221284695829, 0.8617467314595672, 0.8925992788308834, 0.9483694401366933, 0.8971650457417794, 0.8273752237594902, 0.8687073059408716, 0.8648852339344886, 0.8600837808636079, 0.8331002800931575, 0.8829803545146504, 0.8896241315005446, 0.9549800751628035, 0.9592781401565097, 0.9044780256003224, 0.8921260592326554, 0.9556427203087794, 0.977457790370547, 0.9349837539733575]


In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
import numpy as np
import tensorflow as tf
import pandas as pd

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import BatchNormalization
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.decomposition import PCA
from google.colab import drive
drive.mount('/content/drive')

seed=0
np.random.seed(seed)
tf.random.set_seed(seed)

#데이터 입력
df = pd.read_csv('/content/drive/MyDrive/Inhibitor classification/Inhibitor/PA/csv/PA_internal_withothers.csv')
df1 = pd.read_csv('/content/drive/MyDrive/Inhibitor classification/Inhibitor/PA/csv/PA_external_withothers.csv')
df2 = pd.concat([df, df1])

#데이터 분류
#dataset = df.values
#X = dataset[:,0:-1]
#Y = dataset[:,-1]

#ex_data =df1.values
#exX = ex_data[:,0:-1]
#exY = ex_data[:,-1]

tot_data = df2.values
totX = tot_data[:,0:-1]
totY = tot_data[:,-1]

#X 표준화

pca = PCA(n_components=20)

#X_scaled = scaler.fit_transform(X)
#exX_scaled = scaler.transform(exX)
totX_scaled = pca.fit_transform(totX)

#Y 인코딩

#Y_encoded = tf.keras.utils.to_categorical(Y)
#exY_encoded = tf.keras.utils.to_categorical(exY)
totY_encoded = tf.keras.utils.to_categorical(totY)

#k겹 교차검증용 데이터 split

n_fold = 10
skf = StratifiedKFold(n_splits=n_fold, shuffle=True, random_state=seed)

#빈 accu 배열

accuracy = []

#모델 설정, 컴파일, 실행

input_dim = totX_scaled.shape[1]
n_class = 4

for train, test in skf.split(totX_scaled, totY):
    model = Sequential()
    model.add(Dense(1000, input_dim = input_dim, activation='relu'))
    model.add(Dense(500, input_dim = input_dim, activation='relu'))
    model.add(Dense(300, input_dim = input_dim, activation='relu'))
    model.add(Dense(200, input_dim = input_dim, activation='relu'))
    model.add(Dense(100, input_dim = input_dim, activation='relu'))
    model.add(Dense(n_class, activation='softmax'))
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.fit(totX_scaled[train], totY[train], epochs=500, batch_size=5)
    k_accuracy = '%.4f' % (model.evaluate(totX_scaled[test], totY[test])[1])
    accuracy.append(k_accuracy)

#결과 출력 

print('\n %.f fold accuracy:' % n_fold, accuracy)

model.save('PA_ann_0402_2.h5')

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
Epoch 7/500
28/28 [==============================] - 0s 2ms/step - loss: 1175.6037 - accuracy: 0.2885
Epoch 8/500
28/28 [==============================] - 0s 2ms/step - loss: 714.6125 - accuracy: 0.5210
Epoch 9/500
28/28 [==============================] - 0s 3ms/step - loss: 308.7324 - accuracy: 0.3821
Epoch 10/500
28/28 [==============================] - 0s 3ms/step - loss: 153.9510 - accuracy: 0.3764
Epoch 11/500
28/28 [==============================] - 0s 2ms/step - loss: 149.7351 - accuracy: 0.4850
Epoch 12/500
28/28 [==============================] - 0s 2ms/step - loss: 207.7498 - accuracy: 0.3569
Epoch 13/500
28/28 [==============================] - 0s 3ms/step - loss: 402.7594 - accuracy: 0.4071
Epoch 14/500
28/28 [==============================] - 0s 2ms/step - loss: 359.2771 - accuracy: 0.4184
Epoch 15/500
28/28 [==============================] - 0s 2ms/step - loss: 154.7456 - accuracy: 0.5212
Epoch 16/500
28/28 [============================